#Команда для перезагрузки - /cf reload
#Пермишен для перезагрузки - chatfilter.reload
noperm: "&cОшибка - &fНедостаточно прав!"

#Функция, позволяющая админам обходить ограничение из списка blacklist
#Необходим пермишен chatfilter.bypass
admins-bypass: true

#Команды, содержащие указанные слова или символы не будут исполняться.
#Если Вы хотите заблокировать целую команду, то лучше указать как "/op", а не просто "op"
commands:
  message: "Неизвестная команда."
  blacklist:
    - "#"
    - ";"
    - "calc"
    - "minecraft:"
    - "/op"

#Сообщения с словами или символами из этого списка не будут отправлены в чат
chat:
  message: "&cЭто сообщение не может быть отправлено"
  blacklist:
    - "#"
