name: ChatFilter
main: ru.alexey336.filter.Main
version: 1.0
author: Alexey336
description: "Запрет на использование команд или определенных аргументов/символов в них, а так же сообщений, отправляемых в внутриигровой чат"
commands:
  cf:
    description: "ChatFilter"
